Repository theritikchoure/carrierjs, pull requests merged in 2022-10, with the labels that each got.

#6 Adds facebook open graph tags to 2 files
  doc/docs.html
  doc/index.html
Labels: hacktoberfest-accepted

#9 Added contributors.html file with required specifications.
  doc/contributors.html
Labels: hacktoberfest-accepted

#13 added twitter follow badge
  README.md
Labels: hacktoberfest-accepted

#17 Improvement : Add Twitter follow badge in readme file [fixes #16]
  README.md
Labels: hacktoberfest-accepted

#19 Adds twitter card image
  doc/docs.html
  doc/index.html
Labels: enhancement, hacktoberfest-accepted

#22 move pull request template to hidden directory
  .github/pull_request_template.md
Labels: enhancement, hacktoberfest-accepted

#26 feat: Add new "patch" request method
  carrier.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#29 fix: broken images in readme
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#31 Updates site url for the open graph tags
  docs/contributors.html
  docs/docs.html
  docs/index.html
Labels: documentation, enhancement, hacktoberfest-accepted

#32 Newaccounts
  docs/contributors.html
Labels: documentation, enhancement, hacktoberfest-accepted

#33 Added Contributors name in docs/contributors.html
  docs/contributors.html
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#37 feat: add new "timeout" request option
  carrier.js
Labels: enhancement, hacktoberfest-accepted, feature
